# CONFIGURACION PRINCIPAL - LITERALURA
spring.application.name=literalura

# CAMBIAR ESTO PARA ALTERNAR ENTRE BASE DE DATOS:
# 1. h2 (POR DEFECTO - Portable - No requiere instalación, los datos viven en el proyecto)
# 2. postgres (Recomendado Challenge - Requiere Postgres instalado)
spring.profiles.active=h2

# Configuración compartida JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.format-sql=true
